#!/usr/bin/env python3
"""Generate packaging/_AULabsSetup_gen.spec with embedded Server/Agent payload."""

from __future__ import annotations

from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    dist = root / "dist"
    payload_files: list[Path] = []
    for name in ("AULabsServer", "AULabsAgent"):
        for candidate in (
            dist / f"{name}.exe",
            dist / name,
            dist / "payload" / f"{name}.exe",
            dist / "payload" / name,
        ):
            if candidate.exists():
                payload_files.append(candidate.resolve())
                break

    if not payload_files:
        raise SystemExit("No Server/Agent binaries found in dist/. Build them first.")

    datas = [(str(p), "payload") for p in payload_files]
    datas += [
        (str(root / "aulabs"), "aulabs"),
        (str(root / "requirements.txt"), "."),
        (str(root / "README.md"), "."),
    ]
    entry = str(root / "packaging" / "run_setup.py")
    spec = f"""# AUTO-GENERATED by packaging/generate_setup_spec.py — do not edit
block_cipher = None
a = Analysis(
    [{entry!r}],
    pathex=[{str(root)!r}],
    binaries=[],
    datas={datas!r},
    hiddenimports=[
        'aulabs',
        'aulabs.setup_wizard',
        'tkinter',
        '_tkinter',
        'passlib.handlers.bcrypt',
        'bcrypt',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],
    name='AULabsSetup',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
)
"""
    out = root / "packaging" / "_AULabsSetup_gen.spec"
    out.write_text(spec, encoding="utf-8")
    print(f"Wrote {out}")
    for p in payload_files:
        print(f"  payload: {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
